[project]
name = "camera"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=4.0.0",
    "fastapi>=0.124.2",
    "httpx>=0.28.1",
    "ultralytics>=8.3.236",
    "uvicorn>=0.38.0",
]
